# Collector specific configuration
admin_url: "https://api.climatetrace.org/v7/admins/{admin_id}/subdivisions"
cities_url: "https://api.climatetrace.org/v7/cities?country={admin_id}"
emissions_url: "https://api.climatetrace.org/v7/sources/emissions"
source_url: "https://api.climatetrace.org/v7/sources"

gases:
  - "co2e_20yr"
  - "pm2_5"

sectors:
  - "buildings"
  - "mineral-extraction"
  - "manufacturing"
  - "power"
  - "transportation"

dataset_title: "Climate TRACE GHG and non-GHG Emissions Inventory"

tags:
  - climate-weather
  - environment
  - points of interest-poi
